apm-server:
  host: "0.0.0.0:8200"

output.elasticsearch:
  hosts: ["https://es01:9200"]
  username: elastic
  password: "${ELASTIC_PASSWORD}"
  ssl:
    certificate_authorities: ["config/certs/ca/ca.crt"]
    verification_mode: certificate

kibana:
  host: "http://kibana:5601"
  username: elastic
  password: "${ELASTIC_PASSWORD}"

logging.level: info
logging.to_files: true
logging.files:
  path: /var/log/apm-server
  name: apm-server
  keepfiles: 7
  permissions: 0644

monitoring.enabled: true